### ISSUE TITLE
Videos are downloaded without audio

### ISSUE THREAD

**Issue by eddyLazar** [distubejs/ytdl-core#127]
## Describe the bug

Re-opening since not related to the version 

Just trying simple file download using 
```
const video = ytdl(url, {
      quality: "highestvideo",
});
fs.createWriteStream("video.mp4")
```

or just 
```
const video = ytdl(url);
fs.createWriteStream("video.mp4")
```

> And for example it works fine with this video full Joe Rogan Episode - https://www.youtube.com/watch?v=WTNjc8HyOaE 
> But doesn't work with this clip form the same episode - https://www.youtube.com/watch?v=SUPHqTkL5Nw 
> 
> It definitely used to work before I guess soemthing realted to latest changes
> 

From previous issue. This is what is happening to me with lots of videos. Seems like videos are without audios

## Debug File
Here a link to corrupted file https://drive.google.com/file/d/1xM4t84xCbqUdxTHTHmGIXupyHIYBI1Eg/view?usp=drive_link
https://drive.google.com/file/d/1VJmnXzaTVGu2aaIAZ08vD50VnGyYnyWB/view?usp=sharing

## Environment

- @distube/ytdl-core version: ^4.15.1
- Node.js version: 20
- Operating system: Mac OS

**Comment by gulshan-4** [comment]
did anyone find any solution?

**Comment by kosso** [comment]
YouTube no longer provides A+V formats for higher resolutions. 
I had to grab the video and audio files separately and mux them back together with ffmpeg. 

(Also, be careful to select the 'default audio' file too, since you might find the package downloading the wrong language (if available)) 

The only formats which they provide a single A+V file is by requesting "WEB" and/or "ANDROID" playerClients, though it appears to only provide 360p quality.

```
ytdl.getInfo(URL, {
    playerClients: ["WEB", "ANDROID"]
  }).then(info => {
    const formats = ytdl.filterFormats(info.formats, "videoandaudio");
    console.log(formats)
})
```
